// <auto-generated designer code>
namespace GyG.Presentacion
{
    partial class InventarioForm
    {
        private System.ComponentModel.IContainer components = null;

        private System.Windows.Forms.Label lblNombre;
        private System.Windows.Forms.TextBox txtNombre;
        private System.Windows.Forms.Label lblDescripcion;
        private System.Windows.Forms.TextBox txtDescripcion;
        private System.Windows.Forms.Label lblCategoria;
        private System.Windows.Forms.ComboBox cmbCategoria;
        
        private System.Windows.Forms.Label lblPrecioInv;
        private System.Windows.Forms.TextBox txtPrecioInv;
        private System.Windows.Forms.Label lblPrecioVenta;
        private System.Windows.Forms.TextBox txtPrecioVenta;
        private System.Windows.Forms.Label lblStock;
        private System.Windows.Forms.TextBox txtStock;
        private System.Windows.Forms.Label lblCodigoBarra;
        private System.Windows.Forms.TextBox txtCodigoBarra;
        private System.Windows.Forms.DataGridView dgvProductos;
        private System.Windows.Forms.Button btnGuardar;
        private System.Windows.Forms.Button btnEditar;
        private System.Windows.Forms.Button btnEliminar;
        private Button btnEscanearQR;
        private Button btnGestionarCategorias;


        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.lblNombre = new System.Windows.Forms.Label();
            this.txtNombre = new System.Windows.Forms.TextBox();
            this.lblDescripcion = new System.Windows.Forms.Label();
            this.txtDescripcion = new System.Windows.Forms.TextBox();
            this.lblCategoria = new System.Windows.Forms.Label();
            this.cmbCategoria = new System.Windows.Forms.ComboBox();
           
            this.lblPrecioInv = new System.Windows.Forms.Label();
            this.txtPrecioInv = new System.Windows.Forms.TextBox();
            this.lblPrecioVenta = new System.Windows.Forms.Label();
            this.txtPrecioVenta = new System.Windows.Forms.TextBox();
            this.lblStock = new System.Windows.Forms.Label();
            this.txtStock = new System.Windows.Forms.TextBox();
            this.lblCodigoBarra = new System.Windows.Forms.Label();
            this.txtCodigoBarra = new System.Windows.Forms.TextBox();
            this.dgvProductos = new System.Windows.Forms.DataGridView();
            this.btnGuardar = new System.Windows.Forms.Button();
            this.btnEditar = new System.Windows.Forms.Button();
            this.btnEliminar = new System.Windows.Forms.Button();
            this.btnEscanearQR = new System.Windows.Forms.Button();
            this.btnGestionarCategorias = new System.Windows.Forms.Button();

            this.SuspendLayout();

            // Labels and Inputs setup (name, location, size) – simplified
            // Name
            this.lblNombre.Text = "Nombre:";
            this.lblNombre.Location = new System.Drawing.Point(20, 20);
            this.txtNombre.Location = new System.Drawing.Point(120, 20);
            this.txtNombre.Width = 200;

            // Descripción
            this.lblDescripcion.Text = "Descripción:";
            this.lblDescripcion.Location = new System.Drawing.Point(20, 60);
            this.txtDescripcion.Location = new System.Drawing.Point(120, 60);
            this.txtDescripcion.Width = 200;

            // Categoría
            this.lblCategoria.Text = "Categoría (Opcional):";
            this.lblCategoria.Location = new System.Drawing.Point(20, 100);
            this.cmbCategoria.Location = new System.Drawing.Point(120, 100);
            this.cmbCategoria.Width = 200;
            this.btnGestionarCategorias.Text = "+";
            this.btnGestionarCategorias.Click += new System.EventHandler(this.BtnGestionarCategorias_Click);
            this.btnGestionarCategorias.Location = new System.Drawing.Point(330, 100);

            // Precio Inventario
            this.lblPrecioInv.Text = "Precio Inv.:";
            this.lblPrecioInv.Location = new System.Drawing.Point(20, 140);
            this.txtPrecioInv.Location = new System.Drawing.Point(120, 140);
            this.txtPrecioInv.Width = 200;

            // Precio Venta
            this.lblPrecioVenta.Text = "Precio Venta:";
            this.lblPrecioVenta.Location = new System.Drawing.Point(20, 180);
            this.txtPrecioVenta.Location = new System.Drawing.Point(120, 180);
            this.txtPrecioVenta.Width = 200;

            // Stock
            this.lblStock.Text = "Stock:";
            this.lblStock.Location = new System.Drawing.Point(20, 220);
            this.txtStock.Location = new System.Drawing.Point(120, 220);
            this.txtStock.Width = 200;

            // Código de Barra
            this.lblCodigoBarra.Text = "Código:";
            this.lblCodigoBarra.Location = new System.Drawing.Point(20, 260);
            this.txtCodigoBarra.Location = new System.Drawing.Point(120, 260);
            this.txtCodigoBarra.Width = 200;

            // Botones
            this.btnGuardar.Text = "Guardar";
            this.btnGuardar.Location = new System.Drawing.Point(20, 300);

            this.btnEditar.Text = "Editar";
            this.btnEditar.Location = new System.Drawing.Point(120, 300);

            this.btnEliminar.Text = "Eliminar";
            this.btnEliminar.Location = new System.Drawing.Point(220, 300);
            
            this.btnEscanearQR.Text = "Escanear Codigo QR";
            this.btnEscanearQR.Location = new System.Drawing.Point(120, 300);

            // DataGridView
            this.dgvProductos.Location = new System.Drawing.Point(20, 350);
            this.dgvProductos.Size = new System.Drawing.Size(760, 250);
            this.dgvProductos.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvProductos.ScrollBars = ScrollBars.Both;
            this.dgvProductos.ReadOnly = true;
            this.dgvProductos.CellDoubleClick += new DataGridViewCellEventHandler(this.dgvProductos_CellDoubleClick);

            // Form
            this.Controls.Add(this.lblNombre);
            this.Controls.Add(this.txtNombre);
            this.Controls.Add(this.lblDescripcion);
            this.Controls.Add(this.txtDescripcion);
            this.Controls.Add(this.lblCategoria);
            this.Controls.Add(this.cmbCategoria);
            
            this.Controls.Add(this.lblPrecioInv);
            this.Controls.Add(this.txtPrecioInv);
            this.Controls.Add(this.lblPrecioVenta);
            this.Controls.Add(this.txtPrecioVenta);
            this.Controls.Add(this.lblStock);
            this.Controls.Add(this.txtStock);
            this.Controls.Add(this.lblCodigoBarra);
            this.Controls.Add(this.txtCodigoBarra);
            this.Controls.Add(this.btnGuardar);
            this.Controls.Add(this.btnEditar);
            this.Controls.Add(this.btnEliminar);
            this.Controls.Add(this.btnGestionarCategorias);
            this.Controls.Add(this.dgvProductos);

            this.Text = "Gestión de Inventario - GyG";
            this.StartPosition = FormStartPosition.CenterScreen;
            this.ClientSize = new System.Drawing.Size(800, 620);

            this.Load += new System.EventHandler(this.InventarioForm_Load);
            this.ResumeLayout(false);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}